# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
tensor_2=torch.rand(size=(7,7))
tensor_2, tensor_2.shape

(tensor([[0.9246, 0.9639, 0.3500, 0.8789, 0.9002, 0.5929, 0.7217],
         [0.5902, 0.2310, 0.0674, 0.1537, 0.6014, 0.7668, 0.0548],
         [0.9990, 0.9747, 0.8332, 0.9264, 0.4204, 0.3858, 0.6895],
         [0.8379, 0.2804, 0.0177, 0.4172, 0.9798, 0.5391, 0.4265],
         [0.9450, 0.2050, 0.9791, 0.6026, 0.4700, 0.9447, 0.6808],
         [0.7915, 0.7624, 0.0599, 0.1444, 0.1641, 0.7135, 0.3540],
         [0.8286, 0.4235, 0.5153, 0.4083, 0.8214, 0.7629, 0.1317]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor_3 = torch.rand(size=(1,7))
tensor_3 ,tensor_3.ndim, tensor_3.shape

(tensor([[0.9650, 0.3922, 0.0899, 0.7767, 0.5526, 0.2827, 0.5070]]),
 2,
 torch.Size([1, 7]))

In [ ]:

# Perform matrix multiplication 
tensor_7by7 = tensor_2@tensor_3.T
tensor_7by7.shape, tensor_7by7

(torch.Size([7, 1]),
 tensor([[3.0153],
         [1.3624],
         [2.8316],
         [2.1542],
         [2.4201],
         [1.6522],
         [2.0654]]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
import random
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED) 
# Create two random tensors
rtensor_1 = torch.rand(size=(7,7))
rtensor_2 = torch.rand(size=(1,7))

# Matrix multiply tensors
rtensor_3=rtensor_1 @ rtensor_2.T
rtensor_3, rtensor_3.shape


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [2]:
# Set random seed on the GPU
import torch
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
# Set random seed
import torch
torch.manual_seed(1234)

# Check for access to GPU
#!nvidia-smi
print(f"GPU is available {torch.cuda.is_available()}")

# Create two random tensors on GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
rtensor_6a = torch.rand(size=(2,3))
rtensor_6b = torch.rand(size=(2,3))
print(f"Device {device}")

gputensor_6a = rtensor_6a.to(device)
gputensor_6b = rtensor_6b.to(device)

print(f"{gputensor_6a} \n {gputensor_6b}")



GPU is available True
Device cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') 
 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [19]:
# Perform matmul on tensor_A and tensor_B
tensor_7 = torch.matmul(rtensor_6a, rtensor_6b.T)
tensor_7, tensor_7.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]), torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [25]:
# Find max
vmax = tensor_7.max()
print(f"Max value {vmax}")
# Find min
vmin = tensor_7.min()
print(f"Max value {vmin}")

Max value 0.5617256760597229
Max value 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [27]:
# Find arg max
ixmax = tensor_7.argmax()
print(f"Max value {ixmax}")

# Find arg min
ixmin = tensor_7.argmin()
print(f"Max value {ixmin}")

Max value 3
Max value 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [32]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rtensor_10a = torch.rand(size=(1,1,1,10))

# Remove single dimensions
rtensor_10b = rtensor_10a.squeeze(dim=2)

# Print out tensors and their shapes
print(f"{rtensor_10a, rtensor_10a.shape}")
print(f"{rtensor_10b, rtensor_10b.shape}")


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10]))
(tensor([[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
          0.3653, 0.8513]]]), torch.Size([1, 1, 10]))
